export type AppLanguage = 'en' | 'zh';
export type AppTheme = 'light' | 'dark' | 'system';
export type ActiveView = 'editor' | 'preview';
export type ResumeTemplate = 'classic' | 'minimal' | 'standard' | 'sidebar';
export type EditorMode = 'markdown' | 'blocks';

export const resumeTemplates: ResumeTemplate[] = ['classic', 'minimal', 'standard', 'sidebar'];

export const translations = {
  en: {
    editor: 'Markdown Editor',
    export: 'Export',
    exportPdf: 'Export PDF',
    exportWord: 'Export Word',
    exportHtml: 'Export HTML',
    exporting: 'Preparing Print...',
    import: 'Import File',
    importing: 'Importing...',
    extracting: 'Extracting text...',
    parsing: 'Auto-parsing...',
    aiFormatting: 'AI formatting...',
    importFormatting: 'AI is formatting your resume...',
    importNoApiKey: 'API key missing. Imported raw text without AI formatting.',
    importFailed: 'Failed to import the file. Please use a valid PDF, Word, Markdown, or TXT file.',
    template: 'Template',
    markdownMode: 'Markdown',
    blockMode: 'Blocks',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    zoomReset: 'Fit',
    zoomLabel: 'Canvas Zoom',
    classic: 'Classic',
    minimal: 'Minimal',
    standard: 'Standard',
    sidebar: 'Sidebar',
    edit: 'Edit',
    preview: 'Preview',
    themeAuto: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    // BlockEditor labels
    fieldName: 'Name',
    fieldTitle: 'Title',
    fieldContact: 'Contact',
    fieldSummary: 'Summary',
    sectionTitle: 'Section Title',
    entryHeading: 'Heading',
    entryMeta: 'Date',
    entryOrganization: 'Organization',
    entryContent: 'Content',
    deleteSection: 'Delete Section',
    deleteEntry: 'Delete Entry',
    addEntry: 'Add Entry',
    addSection: 'Add Section',
    newEntry: 'New Entry',
    newEntryContent: '- Please fill in content',
    newSection: 'New Section',
    style: 'Style',
    styleEditor: 'Style Editor',
    primaryColor: 'Primary Color',
    secondaryColor: 'Secondary Color',
    colors: 'Colors',
    typography: 'Typography',
    fontFamily: 'Font Family',
    fontSize: 'Font Size',
    lineHeight: 'Line Height',
    sectionSpacing: 'Section Spacing',
    pageMargin: 'Page Margin',
    // Export
    exportSuccess: 'Export successful',
    exportFailed: 'Export failed',
    exportPdfSuccess: 'PDF exported successfully',
    exportWordSuccess: 'Word document exported successfully',
    exportHtmlSuccess: 'HTML exported successfully',
    exportNoPreview: 'Please switch to preview page before exporting',
    // Settings
    settingsTitle: 'Settings',
    tabAi: 'AI Config',
    tabAppearance: 'Appearance',
    tabEditor: 'Editor',
    appearanceTheme: 'Theme Mode',
    appearanceLanguage: 'Interface Language',
    languageZh: 'Chinese',
    languageEn: 'English',
    // AI Settings
    aiProvider: 'AI Provider',
    aiApiKey: 'API Key',
    aiApiKeyPlaceholder: 'Enter your API Key...',
    aiApiKeySecurity: 'API Key is stored locally and sent directly to the AI provider.',
    aiEndpoint: 'API Endpoint',
    aiEndpointPlaceholder: 'https://api.openai.com/v1',
    aiModel: 'Default Model',
    // LLM Config
    llmConfigTitle: 'AI Engine Configuration',
    llmConfigDesc: 'Manage your AI interface credentials',
    llmEndpoint: 'Endpoint',
    llmModel: 'Model',
    llmFetchModels: 'Fetch Models',
    llmFetching: 'Fetching...',
    llmCurrentEngine: 'Current Engine',
    llmSetDefault: 'Set as Default',
    llmApiKeyPlaceholder: 'Enter {name} API Key',
    llmEndpointPlaceholder: 'https://api.openai.com/v1',
    llmCustomModel: 'Custom Model',
    resetToDefault: 'Reset to Default',
    close: 'Close',
    // Misc
    markdownPlaceholder: '# Start writing your resume...',
    toggleLanguage: 'Toggle Language',
    apiSettings: 'API Settings',
    customCss: 'Custom CSS',
    customizeStyles: 'Customize resume styles',
    save: 'Save',
    copy: 'Copy',
    copied: 'Copied!',
  },
  zh: {
    editor: 'Markdown 编辑器',
    export: '导出',
    exportPdf: '导出 PDF',
    exportWord: '导出 Word',
    exportHtml: '导出 HTML',
    exporting: '准备打印中...',
    import: '导入文件',
    importing: '导入中...',
    extracting: '提取文本...',
    parsing: '自动解析...',
    aiFormatting: 'AI 整理中...',
    importFormatting: 'AI 正在整理你的简历内容...',
    importNoApiKey: '未配置 API Key，已导入原始文本，未进行 AI 整理。',
    importFailed: '导入失败，请确认文件是有效的 PDF、Word、Markdown 或 TXT。',
    template: '模板',
    markdownMode: 'Markdown',
    blockMode: '区块编辑',
    zoomIn: '放大',
    zoomOut: '缩小',
    zoomReset: '适应',
    zoomLabel: '画布缩放',
    classic: '经典',
    minimal: '极简',
    standard: '标准',
    sidebar: '侧栏',
    edit: '编辑',
    preview: '预览',
    themeAuto: '跟随系统',
    themeLight: '浅色',
    themeDark: '深色',
    // BlockEditor labels
    fieldName: '姓名',
    fieldTitle: '职位',
    fieldContact: '联系方式',
    fieldSummary: '个人简介',
    sectionTitle: '区块标题',
    entryHeading: '标题',
    entryMeta: '时间',
    entryOrganization: '机构 / 公司',
    entryContent: '内容',
    deleteSection: '删除区块',
    deleteEntry: '删除条目',
    addEntry: '添加条目',
    addSection: '添加区块',
    newEntry: '新条目',
    newEntryContent: '- 请填写内容',
    newSection: '新区块',
    style: '样式',
    styleEditor: '样式编辑器',
    primaryColor: '主色',
    secondaryColor: '辅色',
    colors: '颜色',
    typography: '字体',
    fontFamily: '字体',
    fontSize: '字号',
    lineHeight: '行高',
    sectionSpacing: '区块间距',
    pageMargin: '页边距',
    // Export
    exportSuccess: '导出成功',
    exportFailed: '导出失败',
    exportPdfSuccess: 'PDF 导出成功',
    exportWordSuccess: 'Word 文档导出成功',
    exportHtmlSuccess: 'HTML 导出成功',
    exportNoPreview: '请先切换到预览页后再导出',
    // Settings
    settingsTitle: '设置',
    tabAi: 'AI 配置',
    tabAppearance: '外观',
    tabEditor: '编辑器',
    appearanceTheme: '主题模式',
    appearanceLanguage: '界面语言',
    languageZh: '中文',
    languageEn: 'English',
    // AI Settings
    aiProvider: 'AI 提供商',
    aiApiKey: 'API Key',
    aiApiKeyPlaceholder: '输入你的 API Key...',
    aiApiKeySecurity: 'API Key 保存在本地，每次请求直接发送给模型服务商。',
    aiEndpoint: 'API 地址',
    aiEndpointPlaceholder: 'https://api.openai.com/v1',
    aiModel: '默认模型',
    // LLM Config
    llmConfigTitle: '智能引擎配置',
    llmConfigDesc: '管理您的 AI 接口凭证',
    llmEndpoint: '接口端点',
    llmModel: '模型',
    llmFetchModels: '自动获取模型',
    llmFetching: '获取中...',
    llmCurrentEngine: '当前引擎',
    llmSetDefault: '设为默认引擎',
    llmApiKeyPlaceholder: '输入 {name} API Key',
    llmEndpointPlaceholder: 'https://api.openai.com/v1',
    llmCustomModel: '自定义模型',
    resetToDefault: '恢复默认',
    close: '关闭',
    // Misc
    markdownPlaceholder: '# 开始编写你的简历...',
    toggleLanguage: '切换语言',
    apiSettings: 'API 设置',
    customCss: '自定义 CSS',
    customizeStyles: '修改简历样式',
    save: '保存',
    copy: '复制',
    copied: '已复制!',
  },
} as const;

export type TranslationSet = (typeof translations)[AppLanguage];
