export type AppLanguage = 'en' | 'zh';
export type AppTheme = 'light' | 'dark';
export type ActiveView = 'editor' | 'preview';
export type ResumeTemplate = 'classic' | 'minimal' | 'standard' | 'sidebar';
export type EditorMode = 'markdown' | 'blocks';

export const resumeTemplates: ResumeTemplate[] = ['classic', 'minimal', 'standard', 'sidebar'];

export const translations = {
  en: {
    editor: 'Markdown Editor',
    export: 'Export PDF',
    exporting: 'Preparing Print...',
    import: 'Import File',
    importing: 'Importing...',
    importFormatting: 'AI is formatting your resume...',
    importNoApiKey: 'API key missing. Imported raw text without AI formatting.',
    importFailed: 'Failed to import the file. Please use a valid PDF, Word, Markdown, or TXT file.',
    template: 'Template',
    markdownMode: 'Markdown',
    blockMode: 'Blocks',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    zoomReset: 'Fit',
    zoomLabel: 'Canvas Zoom',
    classic: 'Classic',
    minimal: 'Minimal',
    standard: 'Standard',
    sidebar: 'Sidebar',
    edit: 'Edit',
    preview: 'Preview',
    // BlockEditor labels
    fieldName: 'Name',
    fieldTitle: 'Title',
    fieldContact: 'Contact',
    fieldSummary: 'Summary',
    sectionTitle: 'Section Title',
    entryHeading: 'Heading',
    entryMeta: 'Date',
    entryOrganization: 'Organization',
    entryContent: 'Content',
    deleteSection: 'Delete Section',
    deleteEntry: 'Delete Entry',
    addEntry: 'Add Entry',
    addSection: 'Add Section',
    newEntry: 'New Entry',
    newEntryContent: '- Please fill in content',
    newSection: 'New Section',
  },
  zh: {
    editor: 'Markdown 编辑器',
    export: '导出 PDF',
    exporting: '准备打印中...',
    import: '导入文件',
    importing: '导入中...',
    importFormatting: 'AI 正在整理你的简历内容...',
    importNoApiKey: '未配置 API Key，已导入原始文本，未进行 AI 整理。',
    importFailed: '导入失败，请确认文件是有效的 PDF、Word、Markdown 或 TXT。',
    template: '模板',
    markdownMode: 'Markdown',
    blockMode: '区块编辑',
    zoomIn: '放大',
    zoomOut: '缩小',
    zoomReset: '适应',
    zoomLabel: '画布缩放',
    classic: '经典',
    minimal: '极简',
    standard: '标准',
    sidebar: '侧栏',
    edit: '编辑',
    preview: '预览',
    // BlockEditor labels
    fieldName: '姓名',
    fieldTitle: '职位',
    fieldContact: '联系方式',
    fieldSummary: '个人简介',
    sectionTitle: '区块标题',
    entryHeading: '标题',
    entryMeta: '时间',
    entryOrganization: '机构 / 公司',
    entryContent: '内容',
    deleteSection: '删除区块',
    deleteEntry: '删除条目',
    addEntry: '添加条目',
    addSection: '添加区块',
    newEntry: '新条目',
    newEntryContent: '- 请填写内容',
    newSection: '新区块',
  },
} as const;

export type TranslationSet = (typeof translations)[AppLanguage];
